name = "gols-flamengo-bot"
main = "index.js"
compatibility_date = "2024-06-14"

[[kv_namespaces]]
binding = "GOLS_FLAMENGO_KV"
id = "e49a02d5fd954081931b10619b58bd28"

[[d1_databases]]
binding = "DB"
database_name = "flamengo-db"
database_id = "ebadcee9-18b3-4d13-97f0-edd4b142ed15"

[observability]
enabled = true
