import { getConfig } from "./config.js";

export async function processarBolaoPages(request, env) {
  const url = new URL(request.url);
  if (url.pathname !== "/api/painel-bolao" || request.method !== "GET") return null;

  const bolaoAberto = (await getConfig(env.DB, "bolao_aberto")) || "false";
  const confrontoAtual = (await getConfig(env.DB, "confronto_atual")) || "Nenhum no momento";
  const postAtivoId = (await getConfig(env.DB, "postagem_ativa_id")) || "Nenhum";
  const vencedoresTemp = (await getConfig(env.DB, "vencedores_temporarios")) || "";

  const html = `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gestor do Bolão</title><style>
  :root{--bg:#0b0d10;--card:#161a21;--line:rgba(255,255,255,.08);--red:#dc2626;--green:#16a34a;--blue:#2563eb;--orange:#d97706;--muted:#94a3b8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#f8fafc;font-family:Arial,sans-serif;padding:20px}.wrap{max-width:680px;margin:auto;background:var(--card);border:1px solid var(--line);border-radius:22px;padding:24px}.head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.nav{display:flex;gap:8px}.nav a{background:#1e293b;color:#fff;text-decoration:none;border-radius:10px;padding:10px 12px;font-weight:700}.status{padding:16px;border:1px solid var(--line);border-radius:14px;margin:18px 0}.badge{display:inline-block;padding:5px 10px;border-radius:99px;font-weight:800;font-size:12px}.open{background:rgba(22,163,74,.18);color:#4ade80}.closed{background:rgba(220,38,38,.18);color:#f87171}.section{margin-top:24px;border-top:1px solid var(--line);padding-top:18px}.field{display:flex;flex-direction:column;gap:6px;margin:10px 0}label{font-size:12px;color:var(--muted);font-weight:700;text-transform:uppercase}input,textarea{width:100%;padding:13px;border-radius:10px;border:1px solid var(--line);background:#0b0d10;color:#fff}textarea{min-height:90px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.btn{border:0;border-radius:10px;padding:12px 14px;color:#fff;font-weight:700;cursor:pointer}.green{background:var(--green)}.red{background:var(--red)}.blue{background:var(--blue)}.orange{background:var(--orange)}.purple{background:#7c3aed}.alert{display:none;padding:12px;border-radius:10px;margin:14px 0}@media(max-width:600px){.grid{grid-template-columns:1fr}.wrap{padding:18px}}
  </style></head><body><div class="wrap"><div class="head"><h1>🏆 Gestor do Bolão</h1><div class="nav"><a href="/api/painel-addgoal">⚽ Gols</a><a href="/api/lista-gols">📋 Acervo</a></div></div><div id="msg" class="alert"></div>
  <div class="status"><div>Status: <span class="badge ${bolaoAberto === "true" ? "open" : "closed"}">${bolaoAberto === "true" ? "ABERTO" : "FECHADO"}</span></div><div style="margin-top:8px"><b>Partida:</b> ${confrontoAtual}</div><div style="margin-top:6px;color:var(--muted);font-size:13px"><b>Post ativo:</b> ${postAtivoId}</div></div>
  <div class="section"><h3>⚡ Status dos palpites</h3><div class="grid"><button class="btn green" onclick="statusBolao('true')">🔓 Abrir</button><button class="btn red" onclick="statusBolao('false')">🔒 Fechar</button></div></div>
  <div class="section"><h3>👤 Editar ranking</h3><div class="field"><label>ID Telegram</label><input id="uid"></div><button class="btn blue" onclick="buscarUser()">🔍 Buscar</button><div id="userBox" style="display:none"><div class="field"><label>Nome</label><input id="nome"></div><div class="field"><label>Pontos</label><input type="number" id="pontos"></div><button class="btn green" onclick="salvarUser()">💾 Salvar</button></div></div>
  <div class="section"><h3>🔗 Vincular post existente</h3><div class="field"><label>ID da mensagem</label><input id="postId"></div><div class="field"><label>Confronto</label><input id="vConfronto" value="${confrontoAtual !== "Nenhum no momento" ? confrontoAtual.replace(/"/g,'&quot;') : ""}"></div><button class="btn orange" onclick="vincular()">🔗 Vincular</button></div>
  <div class="section"><h3>🚀 Iniciar novo bolão</h3><div class="field"><label>Confronto / horário</label><input id="confronto"></div><div class="field"><label>FileID da foto</label><input id="foto"></div><button class="btn blue" onclick="iniciar()">🚀 Publicar</button></div>
  <div class="section"><h3>🥇 Vencedores</h3><div class="field"><label>Legenda</label><textarea id="vencedores">${vencedoresTemp}</textarea></div><button class="btn purple" onclick="salvarVencedores()">💾 Salvar</button></div>
  <div class="section"><h3>🏁 Encerrar bolão</h3><div class="field"><label>Placar real</label><input id="placar"></div><div class="field"><label>FileID da foto do resultado (opcional)</label><input id="fotoResultado"></div><button class="btn red" onclick="encerrar()">🏁 Encerrar e publicar</button></div>
  </div><script>
  function aviso(t,ok=true){const m=document.getElementById('msg');m.style.display='block';m.style.background=ok?'#065f46':'#991b1b';m.textContent=t}
  async function req(url,opt={}){const r=await fetch(url,opt);const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Falha');return d}
  async function statusBolao(s){try{await req('/api/bolao-toggle?status='+s,{method:'POST'});aviso('Status alterado.');setTimeout(()=>location.reload(),600)}catch(e){aviso(e.message,false)}}
  async function buscarUser(){try{const d=await req('/api/get-user-details?uid='+encodeURIComponent(uid.value.trim()));nome.value=d.nome||'';pontos.value=d.pontos||0;userBox.style.display='block'}catch(e){aviso(e.message,false)}}
  async function salvarUser(){try{await req('/api/save-user-details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({uid:uid.value.trim(),nome:nome.value.trim(),pontos:pontos.value})});aviso('Dados salvos.')}catch(e){aviso(e.message,false)}}
  async function vincular(){try{await req('/api/bolao-vincular',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({post_id:postId.value.trim(),confronto:vConfronto.value.trim()})});aviso('Post vinculado.');setTimeout(()=>location.reload(),700)}catch(e){aviso(e.message,false)}}
  async function iniciar(){try{const d=await req('/api/bolao-iniciar-web',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confronto:confronto.value.trim(),foto:foto.value.trim()})});aviso('Bolão publicado. ID: '+d.id);setTimeout(()=>location.reload(),900)}catch(e){aviso(e.message,false)}}
  async function salvarVencedores(){try{await req('/api/bolao-vencedores-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({texto:vencedores.value})});aviso('Vencedores salvos.')}catch(e){aviso(e.message,false)}}
  async function encerrar(){try{await req('/api/bolao-encerrar-web',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({placar:placar.value.trim(),foto:fotoResultado.value.trim()})});aviso('Bolão encerrado e ranking atualizado.');setTimeout(()=>location.reload(),1000)}catch(e){aviso(e.message,false)}}
  </script></body></html>`;

  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
